version: "3.6"

networks:
  default:
    external:
      name: desire

services:
  chview:
    image: desire_chview
    container_name: chview
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: run
    volumes:
      - ./src:/usr/src/desire/chview
    ports:
      - "9999:8080"
    networks:
      - default
    env_file:
      - .env
